name: neokdeuri-front-release

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: .env setting
        run: |
          echo "REACT_APP_KAKAO_API_KEY=${{ secrets.REACT_APP_KAKAO_API_KEY }}" >> .env
          echo "REACT_APP_BASE_URL=${{ secrets.REACT_APP_BASE_URL }}" >> .env

      - name: Install Dependencies       # npm 설치
        run: npm install

      - name: Build                      # vue 프로젝트 빌드 파일 생성
        run: npm run build

      - name: Deploy                     # vue 프로젝트 빌드 파일을 Aws S3에 등록
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}          # Github Actions에 등록한 secrets
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  # Github Actions에 등록한 secrets
        run: |
          aws s3 cp --recursive --region ap-northeast-2 \
            build s3://neokdeuri-front-bucket

